package com.example.community.mapper;

import com.example.community.model.RolePermission;
import com.example.community.model.RolePermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Apr 20 21:23:57 EDT 2022
     */
    long countByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Apr 20 21:23:57 EDT 2022
     */
    int deleteByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Apr 20 21:23:57 EDT 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Apr 20 21:23:57 EDT 2022
     */
    int insert(RolePermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Apr 20 21:23:57 EDT 2022
     */
    int insertSelective(RolePermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Apr 20 21:23:57 EDT 2022
     */
    List<RolePermission> selectByExampleWithRowbounds(RolePermissionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Apr 20 21:23:57 EDT 2022
     */
    List<RolePermission> selectByExample(RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Apr 20 21:23:57 EDT 2022
     */
    RolePermission selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Apr 20 21:23:57 EDT 2022
     */
    int updateByExampleSelective(@Param("row") RolePermission row, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Apr 20 21:23:57 EDT 2022
     */
    int updateByExample(@Param("row") RolePermission row, @Param("example") RolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Apr 20 21:23:57 EDT 2022
     */
    int updateByPrimaryKeySelective(RolePermission row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbg.generated Wed Apr 20 21:23:57 EDT 2022
     */
    int updateByPrimaryKey(RolePermission row);
}